# Linux/WSL: mise is preferred; tools are in config/mise/config.toml. Use ./install homebrew only for legacy or macOS.
brew "bat"
#brew "asdf"
brew "fzf"
brew "fd"
# brew "gh"
# brew "git"
brew "lsd"
brew "hub"
brew "jq"
brew "neovim"
# brew "pipx"
brew "uv"
brew "ripgrep"
brew "tmux"
# brew "the_silver_searcher"
brew "zoxide"
brew "starship"
