local abbreviations = {
    teh = "the",
    Teh = "The",
    taht = "that",
    Taht = "That",
    alos = "also",
    Alos = "Also",
    aslo = "also",
    Aslo = "Also",
    becuase = "because",
    Becuase = "Because",
    bianry = "binary",
    Bianry = "Binary",
    bianries = "binaries",
    Bianries = "Binaries",
    charcter = "character",
    Charcter = "Character",
    charcters = "characters",
    Charcters = "Characters",
    exmaple = "example",
    Exmaple = "Example",
    exmaples = "examples",
    Exmaples = "Examples",
    shoudl = "should",
    Shoudl = "Should",
    seperate = "separate",
    Seperate = "Separate",
    fone = "phone",
    Fone = "Phone",
    collectoin = "collection",
    Collectoin = "Collection",
    repostory = "repository",
    Repostory = "Repository",
    allignment = "alignment",
    Allignment = "Alignment",
    refernce = "reference",
    Refernce = "Reference",
    Datacite = "DataCite",
}

for from, to in pairs(abbreviations) do
    vim.cmd(string.format('iab %s %s', from, to))
end
