# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false
[shlvl]
disabled = true
threshold = 1
symbol = "↕️"

[shell]
disabled = false
bash_indicator = ""

# Git status
[git_branch]
truncation_length = 20

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'

[os]
disabled = false
format = "$symbol "
symbols.Ubuntu = ""

# Command duration
[cmd_duration]
min_time = 2000
format = "⏱️ [$duration]($style)"
