# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false
[shlvl]
disabled = false
threshold = 1
symbol = "↕️"

[shell]
disabled = false
bash_indicator = ""

[os]
disabled = false
format = "$symbol "
symbols.Ubuntu = ""
